# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import vector_database_pb2 as proto_dot_vector__database__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/vector_database_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimilaritySearch = channel.unary_unary(
                '/vectordb.VectorDatabaseService/SimilaritySearch',
                request_serializer=proto_dot_vector__database__pb2.SimilaritySearchRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.SimilaritySearchResponse.FromString,
                _registered_method=True)
        self.Upsert = channel.unary_unary(
                '/vectordb.VectorDatabaseService/Upsert',
                request_serializer=proto_dot_vector__database__pb2.UpsertRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.DeleteBySourceFile = channel.unary_unary(
                '/vectordb.VectorDatabaseService/DeleteBySourceFile',
                request_serializer=proto_dot_vector__database__pb2.DeleteBySourceFileRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/vectordb.VectorDatabaseService/Clear',
                request_serializer=proto_dot_vector__database__pb2.ClearRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.ClearResponse.FromString,
                _registered_method=True)
        self.Count = channel.unary_unary(
                '/vectordb.VectorDatabaseService/Count',
                request_serializer=proto_dot_vector__database__pb2.CountRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.CountResponse.FromString,
                _registered_method=True)
        self.GetRecords = channel.unary_unary(
                '/vectordb.VectorDatabaseService/GetRecords',
                request_serializer=proto_dot_vector__database__pb2.GetRecordsRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.GetRecordsResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/vectordb.VectorDatabaseService/Retrieve',
                request_serializer=proto_dot_vector__database__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.UpsertEsChunks = channel.unary_unary(
                '/vectordb.VectorDatabaseService/UpsertEsChunks',
                request_serializer=proto_dot_vector__database__pb2.UpsertEsChunksRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.UpsertEsChunksResponse.FromString,
                _registered_method=True)
        self.DeleteBySourceFileInEs = channel.unary_unary(
                '/vectordb.VectorDatabaseService/DeleteBySourceFileInEs',
                request_serializer=proto_dot_vector__database__pb2.DeleteBySourceFileInEsRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ClearEsIndex = channel.unary_unary(
                '/vectordb.VectorDatabaseService/ClearEsIndex',
                request_serializer=proto_dot_vector__database__pb2.ClearEsIndexRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.ClearResponse.FromString,
                _registered_method=True)
        self.GetEsRuntimeConfig = channel.unary_unary(
                '/vectordb.VectorDatabaseService/GetEsRuntimeConfig',
                request_serializer=proto_dot_vector__database__pb2.GetEsRuntimeConfigRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.GetEsRuntimeConfigResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/vectordb.VectorDatabaseService/HealthCheck',
                request_serializer=proto_dot_vector__database__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_vector__database__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class VectorDatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimilaritySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBySourceFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertEsChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBySourceFileInEs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearEsIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEsRuntimeConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimilaritySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SimilaritySearch,
                    request_deserializer=proto_dot_vector__database__pb2.SimilaritySearchRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.SimilaritySearchResponse.SerializeToString,
            ),
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=proto_dot_vector__database__pb2.UpsertRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.UpsertResponse.SerializeToString,
            ),
            'DeleteBySourceFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBySourceFile,
                    request_deserializer=proto_dot_vector__database__pb2.DeleteBySourceFileRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.DeleteResponse.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=proto_dot_vector__database__pb2.ClearRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.ClearResponse.SerializeToString,
            ),
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=proto_dot_vector__database__pb2.CountRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.CountResponse.SerializeToString,
            ),
            'GetRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecords,
                    request_deserializer=proto_dot_vector__database__pb2.GetRecordsRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.GetRecordsResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=proto_dot_vector__database__pb2.RetrieveRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.RetrieveResponse.SerializeToString,
            ),
            'UpsertEsChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertEsChunks,
                    request_deserializer=proto_dot_vector__database__pb2.UpsertEsChunksRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.UpsertEsChunksResponse.SerializeToString,
            ),
            'DeleteBySourceFileInEs': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBySourceFileInEs,
                    request_deserializer=proto_dot_vector__database__pb2.DeleteBySourceFileInEsRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.DeleteResponse.SerializeToString,
            ),
            'ClearEsIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearEsIndex,
                    request_deserializer=proto_dot_vector__database__pb2.ClearEsIndexRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.ClearResponse.SerializeToString,
            ),
            'GetEsRuntimeConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEsRuntimeConfig,
                    request_deserializer=proto_dot_vector__database__pb2.GetEsRuntimeConfigRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.GetEsRuntimeConfigResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_vector__database__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_vector__database__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectordb.VectorDatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectordb.VectorDatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimilaritySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/SimilaritySearch',
            proto_dot_vector__database__pb2.SimilaritySearchRequest.SerializeToString,
            proto_dot_vector__database__pb2.SimilaritySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/Upsert',
            proto_dot_vector__database__pb2.UpsertRequest.SerializeToString,
            proto_dot_vector__database__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBySourceFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/DeleteBySourceFile',
            proto_dot_vector__database__pb2.DeleteBySourceFileRequest.SerializeToString,
            proto_dot_vector__database__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/Clear',
            proto_dot_vector__database__pb2.ClearRequest.SerializeToString,
            proto_dot_vector__database__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/Count',
            proto_dot_vector__database__pb2.CountRequest.SerializeToString,
            proto_dot_vector__database__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/GetRecords',
            proto_dot_vector__database__pb2.GetRecordsRequest.SerializeToString,
            proto_dot_vector__database__pb2.GetRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/Retrieve',
            proto_dot_vector__database__pb2.RetrieveRequest.SerializeToString,
            proto_dot_vector__database__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertEsChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/UpsertEsChunks',
            proto_dot_vector__database__pb2.UpsertEsChunksRequest.SerializeToString,
            proto_dot_vector__database__pb2.UpsertEsChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBySourceFileInEs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/DeleteBySourceFileInEs',
            proto_dot_vector__database__pb2.DeleteBySourceFileInEsRequest.SerializeToString,
            proto_dot_vector__database__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearEsIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/ClearEsIndex',
            proto_dot_vector__database__pb2.ClearEsIndexRequest.SerializeToString,
            proto_dot_vector__database__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEsRuntimeConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/GetEsRuntimeConfig',
            proto_dot_vector__database__pb2.GetEsRuntimeConfigRequest.SerializeToString,
            proto_dot_vector__database__pb2.GetEsRuntimeConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/HealthCheck',
            proto_dot_vector__database__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_vector__database__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
